version: '3.1'

services:
  db:
    image: postgres
    container_name: payment_system_db
    environment:
      POSTGRES_DB: payment_system
      POSTGRES_USER: amit
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: